image: lovullo/php-ci

include:
    - 'http://devops.pages.lovullo.com/shared-pipelines/jobs-common.yml'
    - 'http://devops.pages.lovullo.com/shared-pipelines/jobs-composer-install.yml'
    - 'http://devops.pages.lovullo.com/shared-pipelines/jobs-php-static-analysis.yml'

variables:
    # Ignores/excludes for static analysis checks
    phpcpd_ignore: '--exclude vendor
                    --exclude app
                    --exclude web
                    --exclude tests
                    --exclude bin
                    --exclude var'

stages:
    - build
    - test
    - deploy

phpcs:
    script:
        - echo "skipping"

phpmd:
    script:
        - echo "skipping"

